# Generated by Django 4.2.14 on 2024-07-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entity', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('incorporation', models.DateField()),
                ('address', models.TextField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('website', models.URLField()),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
